version: "2"

services:

  plex:
    image: jaymoulin/plex
    expose:
      - 32400
      - 33400
    hostname: plex
    volumes:
      - /data/media:/media
    restart: unless-stopped

  transmission:
    image : jaymoulin/transmission
    command: transmission-daemon -f -g /config
    volumes:
      - ./transmission:/config
      - /data/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped

  flexget:
    image: wiserain/flexget:3.3.39
    volumes:
      - ./flexget:/config
      - /data/downloads:/downloads
      - /data/media:/storage
    ports:
      - 5050:5050
    environment:
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=123456
    restart: unless-stopped
    links:
      - transmission
